nodeselector: {}
namespace: devops-ui

images:
  cleaning_pods:
    image: docker.io/s-devops/cleaning-pods
    pullPolicy: IfNotPresent
    tag: "0.1"

variables:
  shared_env:
    APP_ENV: LOCAL

deployments:
  cleaning_pods:
    name: cleaning-pods
    replicas: 1
    labels:
      app: cleaning-pods
    port: 80
    resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 128Mi

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

develop:
  mount: false

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000securityContext

podSecurityContext: {}
  # fsGroup: 2000