version: '3.8'

networks:
  dl_default:
    external: true

services:    
  cleaning-pods:
    build:
      context: $PWD
      dockerfile: .docker/cleaning-pods/Dockerfile
    image: ghcr.io/kkulishov/cleaning-pods/cleaning-pods:0.3
