version: '3.8'

networks:
  dl_default:
    external: true

services:    
  cleaning-pods:
    build:
      context: $PWD
      dockerfile: .docker/cleaning-pods/Dockerfile
    image: ${IMAGE_REGISTRY}:${IMAGE_TAG}
  clickhouse-cronjob:
    build:
      context: $PWD
      dockerfile: .docker/clickhouse-cronjob/Dockerfile
    image: ${IMAGE_REGISTRY_CH_JOB}:${CH_JOB_TAG}    
