---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  shared-env
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.variables.shared_env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}