apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cleaning-pods
  namespace: {{ .Values.namespace }}
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 80
      ttlSecondsAfterFinished: 30
      completions: 1
      template:
        spec:
          serviceAccountName: cleaning-pods
          containers:
            - name: cleaning-pods 
              image: "{{ .Values.images.cleaning_pods.image }}:{{ .Values.images.cleaning_pods.tag }}"
              imagePullPolicy: {{ .Values.images.cleaning_pods.pullPolicy }}
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
              envFrom:
              - configMapRef:
                  name: shared-env
              resources:
                {{- toYaml .Values.deployments.cleaning_pods.resources | nindent 16 }}
          restartPolicy: Never
